feat: Add --tag-pattern option #19 (credit to @LeMimit)
Michael-F-Bryan/auto-changelog pull request #55
Opened 2020-01-18 22:07 UTC by KeNaCo

Notes for @LeMimit 

-  I will split your original PR by feature, so discussion about one will not block merge/release of others 
- I changed your implementation in a way, that irrelevant tags are filtered out during tag_index initialization in Repository. I like to read your opinion about this approach.

2020-02-01 13:17 UTC, LeMimit requested changes

2020-02-01 13:17 UTC, LeMimit commented on auto_changelog/repository.py
> +        for tagref in filter(lambda tagref_: re.search(tag_pattern, tagref_.name), repo.tags):
Hello ! 

This is a good idea to use `filter`. This is less complex than my version. Only one remark, depending on what we want to achieve ` re.search` is not the good function to use. From example, if we take the default semver regex, with the current version of the code the tag "something0.0.0" is taking into account. Because` re.search`  scans through string looking for the first location where the regular expression pattern produces a match. I think this is better to use `re.fullmatch` instead this way we only take tags corresponding to the regex specified.

2020-02-16 17:50 UTC, KeNaCo commented on auto_changelog/repository.py
> +        for tagref in filter(lambda tagref_: re.search(tag_pattern, tagref_.name), repo.tags):
Hi, I'm checking `re.fullmatch` function in [python docs](https://docs.python.org/2/library/re.html) but I don't see any function with this name. Do you mean `re.match`?

2020-02-16 20:04 UTC, LeMimit commented on auto_changelog/repository.py
> +        for tagref in filter(lambda tagref_: re.search(tag_pattern, tagref_.name), repo.tags):
Hello ! You are checking the documentation of python 2.X. Here is the documentation of python 3.8 =>  [Link](https://docs.python.org/3.8/library/re.html#re.fullmatch)

2020-02-16 23:18 UTC, KeNaCo commented on auto_changelog/repository.py
> +        for tagref in filter(lambda tagref_: re.search(tag_pattern, tagref_.name), repo.tags):
Sorry, my bad. I will use it then.

2020-02-23 14:42 UTC, merged